// Code generated by scripts/generate-evidence-models.mjs; DO NOT EDIT.
package store

import "encoding/json"

type Digest = string

type DateTime = string

type JSONValue = any

type Verdict = string

type EvaluationMode = string

type CarrierKind = string

type ProofKind = string

type BindingStatus = string

type ActorRef struct {
	Kind        string  `json:"kind"`
	ID          string  `json:"id"`
	DisplayName string  `json:"displayName"`
	SessionID   *string `json:"sessionId,omitempty"`
}

type EvidenceRecord struct {
	SchemaVersion int      `json:"schemaVersion"`
	ID            string   `json:"id"`
	WorkspaceID   string   `json:"workspaceId"`
	IssueID       string   `json:"issueId"`
	CreatedAt     DateTime `json:"createdAt"`
	CreatedBy     ActorRef `json:"createdBy"`
}

type MaterialSelector struct {
	Kind    string   `json:"kind"`
	Start   *int     `json:"start,omitempty"`
	End     *int     `json:"end,omitempty"`
	Page    *int     `json:"page,omitempty"`
	StartMs *int     `json:"startMs,omitempty"`
	EndMs   *int     `json:"endMs,omitempty"`
	X       *float64 `json:"x,omitempty"`
	Y       *float64 `json:"y,omitempty"`
	Width   *float64 `json:"width,omitempty"`
	Height  *float64 `json:"height,omitempty"`
	Pointer *string  `json:"pointer,omitempty"`
}

type ReferenceMedia struct {
	MaterialID string            `json:"materialId"`
	Role       string            `json:"role"`
	Caption    string            `json:"caption"`
	Selector   *MaterialSelector `json:"selector,omitempty"`
}

type RichContent struct {
	Text  string           `json:"text"`
	Media []ReferenceMedia `json:"media"`
}

type EvidenceRequirement struct {
	ID               string        `json:"id"`
	Description      string        `json:"description"`
	AcceptedCarriers []CarrierKind `json:"acceptedCarriers"`
	MinimumCount     int           `json:"minimumCount"`
	BindingPolicy    string        `json:"bindingPolicy"`
}

type SecretBinding struct {
	Name          string `json:"name"`
	CredentialRef string `json:"credentialRef"`
}

type CheckConfiguration struct {
	Kind                    string               `json:"kind"`
	Executable              *string              `json:"executable,omitempty"`
	Args                    []string             `json:"args,omitempty"`
	CwdRelativePath         *string              `json:"cwdRelativePath,omitempty"`
	CheckerBundleMaterialID *string              `json:"checkerBundleMaterialId,omitempty"`
	Entrypoint              *string              `json:"entrypoint,omitempty"`
	FixtureMaterialIDs      []string             `json:"fixtureMaterialIds,omitempty"`
	Environment             map[string]string    `json:"environment,omitempty"`
	SecretBindings          []SecretBinding      `json:"secretBindings,omitempty"`
	ExpectedExitCodes       []int                `json:"expectedExitCodes,omitempty"`
	ResultFormat            *string              `json:"resultFormat,omitempty"`
	MinimumAssertions       *int                 `json:"minimumAssertions,omitempty"`
	TargetName              *string              `json:"targetName,omitempty"`
	Method                  *string              `json:"method,omitempty"`
	Path                    *string              `json:"path,omitempty"`
	Headers                 map[string]string    `json:"headers,omitempty"`
	BodyMaterialID          *string              `json:"bodyMaterialId,omitempty"`
	ExpectedStatus          *int                 `json:"expectedStatus,omitempty"`
	ExpectedHeaders         map[string]string    `json:"expectedHeaders,omitempty"`
	ExpectedJsonValues      map[string]JSONValue `json:"expectedJsonValues,omitempty"`
}

type CheckDefinition struct {
	ID               string             `json:"id"`
	Version          int                `json:"version"`
	Description      string             `json:"description"`
	DefinitionDigest Digest             `json:"definitionDigest"`
	TimeoutMs        int                `json:"timeoutMs"`
	Configuration    CheckConfiguration `json:"configuration"`
}

type AcceptanceCriterion struct {
	ID                    string                `json:"id"`
	Title                 string                `json:"title"`
	Statement             string                `json:"statement"`
	Required              bool                  `json:"required"`
	ProofKind             ProofKind             `json:"proofKind"`
	ProofKindLabel        *string               `json:"proofKindLabel,omitempty"`
	EvaluationMode        EvaluationMode        `json:"evaluationMode"`
	Rubric                RichContent           `json:"rubric"`
	EvidenceRequirements  []EvidenceRequirement `json:"evidenceRequirements"`
	Checker               *CheckDefinition      `json:"checker,omitempty"`
	MaxEvidenceAgeSeconds *int                  `json:"maxEvidenceAgeSeconds,omitempty"`
}

type ContractContent struct {
	Goal        RichContent           `json:"goal"`
	InScope     []string              `json:"inScope"`
	OutOfScope  []string              `json:"outOfScope"`
	Constraints []string              `json:"constraints"`
	Criteria    []AcceptanceCriterion `json:"criteria"`
}

type ContractConfirmation struct {
	Actor         ActorRef `json:"actor"`
	At            DateTime `json:"at"`
	ContentDigest Digest   `json:"contentDigest"`
}

type IssueContract struct {
	SchemaVersion   int                   `json:"schemaVersion"`
	ID              string                `json:"id"`
	WorkspaceID     string                `json:"workspaceId"`
	IssueID         string                `json:"issueId"`
	CreatedAt       DateTime              `json:"createdAt"`
	CreatedBy       ActorRef              `json:"createdBy"`
	Goal            RichContent           `json:"goal"`
	InScope         []string              `json:"inScope"`
	OutOfScope      []string              `json:"outOfScope"`
	Constraints     []string              `json:"constraints"`
	Criteria        []AcceptanceCriterion `json:"criteria"`
	Revision        int                   `json:"revision"`
	BasedOnRevision *int                  `json:"basedOnRevision,omitempty"`
	Origin          string                `json:"origin"`
	ChangeReason    *string               `json:"changeReason,omitempty"`
	ContentDigest   Digest                `json:"contentDigest"`
	Status          string                `json:"status"`
	Confirmation    *ContractConfirmation `json:"confirmation,omitempty"`
}

type MaterialTransformation struct {
	Kind    string `json:"kind"`
	Tool    string `json:"tool"`
	Version string `json:"version"`
}

type MaterialRedaction struct {
	Status        string  `json:"status"`
	PolicyVersion *string `json:"policyVersion,omitempty"`
	Note          *string `json:"note,omitempty"`
}

type Material struct {
	SchemaVersion         int                     `json:"schemaVersion"`
	ID                    string                  `json:"id"`
	WorkspaceID           string                  `json:"workspaceId"`
	IssueID               string                  `json:"issueId"`
	CreatedAt             DateTime                `json:"createdAt"`
	CreatedBy             ActorRef                `json:"createdBy"`
	Name                  string                  `json:"name"`
	Carrier               CarrierKind             `json:"carrier"`
	MimeType              string                  `json:"mimeType"`
	ByteSize              int                     `json:"byteSize"`
	Digest                Digest                  `json:"digest"`
	StorageDeviceID       string                  `json:"storageDeviceId"`
	CapturedAt            DateTime                `json:"capturedAt"`
	DerivedFromMaterialID *string                 `json:"derivedFromMaterialId,omitempty"`
	Transformation        *MaterialTransformation `json:"transformation,omitempty"`
	Redaction             MaterialRedaction       `json:"redaction"`
	PreviewMaterialIDs    []string                `json:"previewMaterialIds"`
	Availability          string                  `json:"availability"`
	AvailabilityCheckedAt DateTime                `json:"availabilityCheckedAt"`
}

type SnapshotRepository struct {
	RepoID          string  `json:"repoId"`
	RelativePath    string  `json:"relativePath"`
	Kind            string  `json:"kind"`
	ParentRepoID    *string `json:"parentRepoId,omitempty"`
	BaselineRef     string  `json:"baselineRef"`
	BaselineCommit  string  `json:"baselineCommit"`
	CandidateCommit string  `json:"candidateCommit"`
	TreeOid         string  `json:"treeOid"`
}

type SnapshotFile struct {
	RepoID string `json:"repoId"`
	Path   string `json:"path"`
	Kind   string `json:"kind"`
	Mode   string `json:"mode"`
	Digest string `json:"digest"`
}

type CandidateSnapshot struct {
	SchemaVersion          int                  `json:"schemaVersion"`
	ID                     string               `json:"id"`
	WorkspaceID            string               `json:"workspaceId"`
	IssueID                string               `json:"issueId"`
	CreatedAt              DateTime             `json:"createdAt"`
	CreatedBy              ActorRef             `json:"createdBy"`
	EnvironmentID          string               `json:"environmentId"`
	EnvironmentRevision    int                  `json:"environmentRevision"`
	Purpose                string               `json:"purpose"`
	ParentSnapshotID       *string              `json:"parentSnapshotId,omitempty"`
	Repositories           []SnapshotRepository `json:"repositories"`
	FileManifestMaterialID string               `json:"fileManifestMaterialId"`
	ContentDigest          Digest               `json:"contentDigest"`
	CapturedAt             DateTime             `json:"capturedAt"`
}

type EnvironmentSnapshotToolsItem struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type EnvironmentSnapshotResource struct {
	Kind            string `json:"kind"`
	InstanceID      string `json:"instanceId"`
	Provider        string `json:"provider"`
	ProviderVersion string `json:"providerVersion"`
}

type EnvironmentSnapshot struct {
	DeviceID               string                         `json:"deviceId"`
	ExecutionEnvironmentID string                         `json:"executionEnvironmentId"`
	Os                     string                         `json:"os"`
	Architecture           string                         `json:"architecture"`
	Tools                  []EnvironmentSnapshotToolsItem `json:"tools"`
	ConfigurationDigest    string                         `json:"configurationDigest"`
	Resource               *EnvironmentSnapshotResource   `json:"resource,omitempty"`
}

type InputDependency struct {
	Name         string  `json:"name"`
	Kind         string  `json:"kind"`
	SourceLabel  string  `json:"sourceLabel"`
	VersionToken string  `json:"versionToken"`
	MaterialID   *string `json:"materialId,omitempty"`
	Revalidation string  `json:"revalidation"`
}

type TargetSnapshotBuild struct {
	Digest                    string  `json:"digest"`
	SourceCandidateSnapshotID string  `json:"sourceCandidateSnapshotId"`
	MaterialID                *string `json:"materialId,omitempty"`
	ProducerDeviceID          string  `json:"producerDeviceId"`
}

type TargetSnapshot struct {
	Name             string               `json:"name"`
	Kind             string               `json:"kind"`
	LocatorLabel     string               `json:"locatorLabel"`
	InstanceID       *string              `json:"instanceId,omitempty"`
	Build            *TargetSnapshotBuild `json:"build,omitempty"`
	ObservedIdentity string               `json:"observedIdentity"`
	IdentityMethod   string               `json:"identityMethod"`
	BindingStatus    BindingStatus        `json:"bindingStatus"`
	ObservedAt       DateTime             `json:"observedAt"`
}

type VerificationInput struct {
	SchemaVersion       int                 `json:"schemaVersion"`
	ID                  string              `json:"id"`
	WorkspaceID         string              `json:"workspaceId"`
	IssueID             string              `json:"issueId"`
	CreatedAt           DateTime            `json:"createdAt"`
	CreatedBy           ActorRef            `json:"createdBy"`
	ContractRevision    int                 `json:"contractRevision"`
	ContractDigest      Digest              `json:"contractDigest"`
	CandidateSnapshotID string              `json:"candidateSnapshotId"`
	CandidateDigest     Digest              `json:"candidateDigest"`
	Environment         EnvironmentSnapshot `json:"environment"`
	Dependencies        []InputDependency   `json:"dependencies"`
	Targets             []TargetSnapshot    `json:"targets"`
	InputDigest         Digest              `json:"inputDigest"`
	BindingStatus       BindingStatus       `json:"bindingStatus"`
	BindingNotes        []string            `json:"bindingNotes"`
}

type EvidenceClaim struct {
	CriterionID   string `json:"criterionId"`
	RequirementID string `json:"requirementId"`
	Purpose       string `json:"purpose"`
}

type EvidenceMaterialRef struct {
	MaterialID string `json:"materialId"`
	Role       string `json:"role"`
}

type EvidenceSource struct {
	Kind       string   `json:"kind"`
	Producer   ActorRef `json:"producer"`
	DeviceID   *string  `json:"deviceId,omitempty"`
	RunID      *string  `json:"runId,omitempty"`
	SessionID  *string  `json:"sessionId,omitempty"`
	ToolCallID *string  `json:"toolCallId,omitempty"`
}

type CollectionRecordError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type CollectionRecord struct {
	Operation        string                 `json:"operation"`
	CollectorName    string                 `json:"collectorName"`
	CollectorVersion string                 `json:"collectorVersion"`
	InputMaterialID  string                 `json:"inputMaterialId"`
	StartedAt        DateTime               `json:"startedAt"`
	FinishedAt       DateTime               `json:"finishedAt"`
	Outcome          string                 `json:"outcome"`
	ExitCode         *int                   `json:"exitCode,omitempty"`
	HttpStatus       *int                   `json:"httpStatus,omitempty"`
	Error            *CollectionRecordError `json:"error,omitempty"`
	Completeness     string                 `json:"completeness"`
}

type EvidenceBindingAttestation struct {
	Actor     ActorRef `json:"actor"`
	At        DateTime `json:"at"`
	Statement string   `json:"statement"`
}

type Evidence struct {
	SchemaVersion        int                         `json:"schemaVersion"`
	ID                   string                      `json:"id"`
	WorkspaceID          string                      `json:"workspaceId"`
	IssueID              string                      `json:"issueId"`
	CreatedAt            DateTime                    `json:"createdAt"`
	CreatedBy            ActorRef                    `json:"createdBy"`
	Title                string                      `json:"title"`
	Description          string                      `json:"description"`
	VerificationInputID  string                      `json:"verificationInputId"`
	Claims               []EvidenceClaim             `json:"claims"`
	Materials            []EvidenceMaterialRef       `json:"materials"`
	Source               EvidenceSource              `json:"source"`
	Collection           CollectionRecord            `json:"collection"`
	CandidateBinding     string                      `json:"candidateBinding"`
	BindingAttestation   *EvidenceBindingAttestation `json:"bindingAttestation,omitempty"`
	SupersedesEvidenceID *string                     `json:"supersedesEvidenceId,omitempty"`
}

type VerifierIdentity struct {
	Kind                  string  `json:"kind"`
	Name                  *string `json:"name,omitempty"`
	Version               *string `json:"version,omitempty"`
	CheckerDigest         *string `json:"checkerDigest,omitempty"`
	Harness               *string `json:"harness,omitempty"`
	ProfileID             *string `json:"profileId,omitempty"`
	RequestedModel        *string `json:"requestedModel,omitempty"`
	ReportedModel         *string `json:"reportedModel,omitempty"`
	SessionID             *string `json:"sessionId,omitempty"`
	PromptTemplateVersion *string `json:"promptTemplateVersion,omitempty"`
	PromptDigest          *string `json:"promptDigest,omitempty"`
	Isolated              *bool   `json:"isolated,omitempty"`
}

type EvidenceCitation struct {
	EvidenceID string            `json:"evidenceId"`
	MaterialID string            `json:"materialId"`
	Selector   *MaterialSelector `json:"selector,omitempty"`
}

type ReferenceCitation struct {
	MaterialID string            `json:"materialId"`
	Selector   *MaterialSelector `json:"selector,omitempty"`
}

type VerificationFinding struct {
	ID                 string              `json:"id"`
	Statement          string              `json:"statement"`
	Expected           string              `json:"expected"`
	Observed           string              `json:"observed"`
	Verdict            Verdict             `json:"verdict"`
	EvidenceCitations  []EvidenceCitation  `json:"evidenceCitations"`
	ReferenceCitations []ReferenceCitation `json:"referenceCitations"`
}

type VerificationResult struct {
	Verdict             Verdict               `json:"verdict"`
	Summary             string                `json:"summary"`
	Reasoning           string                `json:"reasoning"`
	Findings            []VerificationFinding `json:"findings"`
	Limitations         []string              `json:"limitations"`
	UnmetRequirementIDs []string              `json:"unmetRequirementIds"`
	RawOutputMaterialID string                `json:"rawOutputMaterialId"`
	ReportMaterialID    string                `json:"reportMaterialId"`
	CompletedAt         DateTime              `json:"completedAt"`
}

type VerificationError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

type Verification struct {
	SchemaVersion            int                 `json:"schemaVersion"`
	ID                       string              `json:"id"`
	WorkspaceID              string              `json:"workspaceId"`
	IssueID                  string              `json:"issueId"`
	CreatedAt                DateTime            `json:"createdAt"`
	CreatedBy                ActorRef            `json:"createdBy"`
	Sequence                 int                 `json:"sequence"`
	CriterionID              string              `json:"criterionId"`
	ContractRevision         int                 `json:"contractRevision"`
	VerificationInputID      string              `json:"verificationInputId"`
	EvidenceIDs              []string            `json:"evidenceIds"`
	Mode                     EvaluationMode      `json:"mode"`
	Executor                 VerifierIdentity    `json:"executor"`
	Status                   string              `json:"status"`
	StartedAt                *DateTime           `json:"startedAt,omitempty"`
	FinishedAt               *DateTime           `json:"finishedAt,omitempty"`
	Result                   *VerificationResult `json:"result,omitempty"`
	Error                    *VerificationError  `json:"error,omitempty"`
	SupersedesVerificationID *string             `json:"supersedesVerificationId,omitempty"`
}

type HumanAssessment struct {
	SchemaVersion          int                `json:"schemaVersion"`
	ID                     string             `json:"id"`
	WorkspaceID            string             `json:"workspaceId"`
	IssueID                string             `json:"issueId"`
	CreatedAt              DateTime           `json:"createdAt"`
	CreatedBy              ActorRef           `json:"createdBy"`
	CriterionID            string             `json:"criterionId"`
	ContractRevision       int                `json:"contractRevision"`
	VerificationInputID    string             `json:"verificationInputId"`
	VerificationID         string             `json:"verificationId"`
	Verdict                Verdict            `json:"verdict"`
	Rationale              RichContent        `json:"rationale"`
	EvidenceCitations      []EvidenceCitation `json:"evidenceCitations"`
	SupersedesAssessmentID *string            `json:"supersedesAssessmentId,omitempty"`
}

type CriterionReviewEntry struct {
	CriterionID          string   `json:"criterionId"`
	VerificationID       *string  `json:"verificationId,omitempty"`
	HumanAssessmentID    *string  `json:"humanAssessmentId,omitempty"`
	EvidenceIDs          []string `json:"evidenceIds"`
	EffectiveVerdict     string   `json:"effectiveVerdict"`
	Authority            string   `json:"authority"`
	Freshness            string   `json:"freshness"`
	EvidenceAvailability string   `json:"evidenceAvailability"`
	Reasons              []string `json:"reasons"`
}

type ReviewBlocker struct {
	Code        string  `json:"code"`
	CriterionID *string `json:"criterionId,omitempty"`
	Message     string  `json:"message"`
}

type ReviewSnapshot struct {
	SchemaVersion       int                    `json:"schemaVersion"`
	ID                  string                 `json:"id"`
	WorkspaceID         string                 `json:"workspaceId"`
	IssueID             string                 `json:"issueId"`
	CreatedAt           DateTime               `json:"createdAt"`
	CreatedBy           ActorRef               `json:"createdBy"`
	ContractRevision    int                    `json:"contractRevision"`
	CandidateSnapshotID string                 `json:"candidateSnapshotId"`
	CriterionResults    []CriterionReviewEntry `json:"criterionResults"`
	BlockingReasons     []ReviewBlocker        `json:"blockingReasons"`
	Eligible            bool                   `json:"eligible"`
	Digest              Digest                 `json:"digest"`
}

type AcceptanceDecision struct {
	SchemaVersion       int          `json:"schemaVersion"`
	ID                  string       `json:"id"`
	WorkspaceID         string       `json:"workspaceId"`
	IssueID             string       `json:"issueId"`
	CreatedAt           DateTime     `json:"createdAt"`
	CreatedBy           ActorRef     `json:"createdBy"`
	ReviewSnapshotID    string       `json:"reviewSnapshotId"`
	ReviewDigest        Digest       `json:"reviewDigest"`
	ContractRevision    int          `json:"contractRevision"`
	CandidateSnapshotID string       `json:"candidateSnapshotId"`
	Rationale           *RichContent `json:"rationale,omitempty"`
	Status              string       `json:"status"`
	InvalidatedAt       *DateTime    `json:"invalidatedAt,omitempty"`
	InvalidationReason  *string      `json:"invalidationReason,omitempty"`
	IntegrationID       *string      `json:"integrationId,omitempty"`
}

type AuditEventSubject struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}

type AuditEvent struct {
	SchemaVersion int               `json:"schemaVersion"`
	ID            string            `json:"id"`
	WorkspaceID   string            `json:"workspaceId"`
	IssueID       string            `json:"issueId"`
	CreatedAt     DateTime          `json:"createdAt"`
	CreatedBy     ActorRef          `json:"createdBy"`
	Sequence      int               `json:"sequence"`
	Action        string            `json:"action"`
	Subject       AuditEventSubject `json:"subject"`
	BeforeDigest  *Digest           `json:"beforeDigest,omitempty"`
	AfterDigest   *Digest           `json:"afterDigest,omitempty"`
	Reason        *string           `json:"reason,omitempty"`
	RequestID     string            `json:"requestId"`
}

type VerificationSummary struct {
	RequiredTotal int  `json:"requiredTotal"`
	Passed        int  `json:"passed"`
	Failed        int  `json:"failed"`
	Inconclusive  int  `json:"inconclusive"`
	Pending       int  `json:"pending"`
	Stale         int  `json:"stale"`
	Eligible      bool `json:"eligible"`
}

type ContractDraftInput struct {
	BaseRevision *int            `json:"baseRevision,omitempty"`
	Content      ContractContent `json:"content"`
	ChangeReason *string         `json:"changeReason,omitempty"`
}

type CheckAssertion struct {
	ID       string    `json:"id"`
	Expected JSONValue `json:"expected"`
	Observed JSONValue `json:"observed"`
	Verdict  Verdict   `json:"verdict"`
}

type CheckReport struct {
	Assertions []CheckAssertion `json:"assertions"`
}

func (v MaterialSelector) MarshalJSON() ([]byte, error) {
	type plain MaterialSelector
	raw, err := json.Marshal(plain(v))
	if err != nil {
		return nil, err
	}
	return marshalEvidenceUnion("MaterialSelector", v.Kind, raw)
}

func (v CheckConfiguration) MarshalJSON() ([]byte, error) {
	type plain CheckConfiguration
	raw, err := json.Marshal(plain(v))
	if err != nil {
		return nil, err
	}
	return marshalEvidenceUnion("CheckConfiguration", v.Kind, raw)
}

func (v VerifierIdentity) MarshalJSON() ([]byte, error) {
	type plain VerifierIdentity
	raw, err := json.Marshal(plain(v))
	if err != nil {
		return nil, err
	}
	return marshalEvidenceUnion("VerifierIdentity", v.Kind, raw)
}
